### ISSUE TITLE
Problem when installed in kanboard

### ISSUE THREAD

**Issue by lafaurie** [stinnux/kanboard-Timetrackingeditor#11]
I have these issues 

`Warning: Illegal string offset 'template' in /srv/www/htdocs/kanboard/app/Helper/HookHelper.php on line 29

Warning: filemtime(): stat failed for p in /srv/www/htdocs/kanboard/app/Helper/AssetHelper.php on line 37`

tested in kanboard 1.37 and 1.39 with plugin version 0.0.1 and 1.0.0

**Comment by stinnux** [comment]
Can you try version 1.0.14?

**Comment by lafaurie** [comment]
Now its works thanks
