### ISSUE TITLE
doesn't work with KB 1.0.41

### ISSUE THREAD

**Issue by thob** [stinnux/kanboard-Timetrackingeditor#13]
the task view is broken when subtasks are (have been) added.

**Comment by bla-kw** [comment]
`PHP Fatal error:  Uncaught Error: Call to undefined method Kanboard\Plugin\Timetrackingeditor\Helper\SubtaskHelper::getTitle() in /var/www/app/plugins/Timetrackingeditor/Helper/SubtaskHelper.php:38`

https://github.com/kanboard/kanboard/commit/f3deb6492a74f1ffa9e3391274e0ab7947a04016#diff-81f825582ee0ed99e1b29bf71635e5a2L15
Looks like getTitle was renamed to renderTitle

**Comment by stinnux** [comment]
I have updated the Plugin to Version 1.0.16. Please give it a try.
