### ISSUE TITLE
Compatibility with the latest release

### ISSUE THREAD

**Issue by izno** [stinnux/kanboard-Timetrackingeditor#16]
@stinnux Thank you for this plugin. I think it's exactly what lacks at the moment to be able to control all the tracked time etc... 

Is it possible to update this so it works with the latest version "Kanboard 1.0.44"? ...or guide me to understand where to start if I need to do it my self.

Thank you in advanced

**Comment by andreapx** [comment]
Enterina a task that has subtasks I get this error:
Fatal error: Call to undefined method Kanboard\Helper\SubtaskHelper::renderToggleStatus() in /var/www/ticket_emmegisistemi/plugins/Timetrackingeditor/Template/subtask/table.php on line 23

**Comment by NielBuys** [comment]
Same here, I had to uninstall the plugin after upgrade.

**Comment by izno** [comment]
@NielBuys I've found the issue... just disable the requirement for the version in the Plugin.php or just update it to the current version.

```
    public function getCompatibleVersion()
    {
	return '1.0.41';
    }
```
I think the plug-in works fine in 1.0.45 (current version at this time).

**Comment by NielBuys** [comment]
@izno Thanks for reply, I tested now again, I downloaded the newest zip from the Kanboard site, when I open any task with sub tasks, the screen don't render correctly and I get an error in my apache log. I run the newest version of Kanboard 1.0.45. 
Maybe I have a different problem I will create another issue.
Error: 
`PHP Fatal error:  Uncaught Error: Call to undefined method Kanboard\\Plugin\\Timetrackingeditor\\Helper\\SubtaskHelper::getTitle() in /var/www/html/kanboard/plugins/Timetrackingeditor/Helper/SubtaskHelper.php:38\nStack trace:\n#0 /var/www/html/kanboard/plugins/Timetrackingeditor/Template/subtask/table.php(23): Kanboard\\Plugin\\Timetrackingeditor\\Helper\\SubtaskHelper->toggleStatus(Array, '4', true)\n#1 /var/www/html/kanboard/app/Core/Template.php(83): include('/var/www/html/k...')\n#2 /var/www/html/kanboard/app/Template/subtask/show.php(9): Kanboard\\Core\\Template->render('subtask/table', Array)\n#3 /var/www/html/kanboard/app/Core/Template.php(83): include('/var/www/html/k...')\n#4 /var/www/html/kanboard/app/Template/task/show.php(21): Kanboard\\Core\\Template->render('subtask/show', Array)\n#5 /var/www/html/kanboard/app/Core/Template.php(83): include('/var/www/html/k...')\n#6 /var/www/html/kanboard/app/Helper/LayoutHelper.php(205): Kanboard\\Core\\Template->render('task/show', Array)\n#7 /var/www/html/kanboard/app/Helper/LayoutHelper.php(72): Ka in /var/www/html/kanboard/plugins/Timetrackingeditor/Helper/SubtaskHelper.php on line 38 `

**Comment by dmth** [comment]
I have a similar Issue like Niel: 

 - KanBoard 1.0.44
 - Timetrackingeditor 1.14

It happens on Tasks with Subtasks.

```
PHP Fatal error:  Call to undefined method Kanboard\\Plugin\\Timetrackingeditor\\Helper\\SubtaskHelper::getTitle() in /var/www/html/plugins/Timetrackingeditor/Helper/SubtaskHelper.php on line 38
```

**Comment by NielBuys** [comment]
dmth use github version the error is gone there, error only occurs on kanboard website version. You need to change the kanboard version number in the addon config file before it will work.
If you are interested I forked the github version to do the version change if you just want to download that version. https://github.com/NielBuys/kanboard-Timetrackingeditor

**Comment by dmth** [comment]
Thank you for the hint, I already use a git-clone and thought 1.14 would be the newest version, but the version-numbers seem to be a little messed up here: 0.0.3 < 1.1.0 < 1.1.3 < 1.14 < 1.0.15 and so on.

**Comment by stinnux** [comment]
Please try version 1.0.18
