### ISSUE TITLE
date.timezone

### ISSUE THREAD

**Issue by andreapx** [stinnux/kanboard-Timetrackingeditor#17]
After installing the plugin I get this warning:

Warning: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /var/www/ticket_emmegisistemi/vendor/fguillot/simpleLogger/src/SimpleLogger/Base.php on line 87

For now I've just added "date_default_timezone_set('Europe/Rome');" in that file.
Thanks!

**Comment by stinnux** [comment]
i don't think that is related to the timetrackingeditor
