### ISSUE TITLE
Can't "add/remove/delete entries"

### ISSUE THREAD

**Issue by andreapx** [stinnux/kanboard-Timetrackingeditor#18]
I can list all the time tracking, but I can't "add/remove/delete entries" (I guess that "remove" is an error for "edit"), nor add comments and select billable/not billable to time tracking entries.
Here is my configuration:
    Application version: 1.0.45
    PHP version: 5.6.24-pl0-gentoo
    PHP SAPI: apache2handler
    OS version: Linux 3.4.111
    Database driver: mysql
    Database version: 10.0.23-MariaDB-log
    Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0
Thanks!

**Comment by stinnux** [comment]
Please try version 1.0.18
