### ISSUE TITLE
FATAL ERROR: SubtasktimetrackingModel not found

### ISSUE THREAD

**Issue by pfabri** [stinnux/kanboard-Timetrackingeditor#2]
Dear Stinnux,

Thanks for the plugin, it works well mostly. However, it seems to have crippled the timer function originally built into Kanboard.

If I create a subtask and click 'start timer' I get the following error: 
`Fatal error: Class '\Kanboard\Plugin\Timetrackingeditor\Model\SubtasktimetrackingModel' not found in /home/myfolder/public_html/myfolder2/app/Core/Tool.php on line 58`

What might the problem be? I also had to manually import the mysql schema, as it wasn't automatically imported by the php script.

Thank you in advance.

**Comment by stinnux** [comment]
which version of kanboard are you using?
