### ISSUE TITLE
Tags and Version-Numbers

### ISSUE THREAD

**Issue by dmth** [stinnux/kanboard-Timetrackingeditor#20]
Thomas,
thank you very much for creating and maintaining this plugin.

The version-numbers seem to be a little bit messed up, but you already tidied that up, which ist good.

Maybe you can also remove the outdated / wrong Tags 1.13, 1.14, and so on, because when looking through the name of the tags it seems like 1.14 is newer than 1.0.15.

BTW: The version tagged 1.0.16 is a 1.0.15 in the Plugin.php
https://github.com/stinnux/kanboard-Timetrackingeditor/blob/1.0.16/Plugin.php#L79

**Comment by stinnux** [comment]
Good Point. I removed all the tags/releases that used the old version scheme
