### ISSUE TITLE
Fatal Error: Call to undefined method [...]SubtaskHelper::getTitle()

### ISSUE THREAD

**Issue by tschroeder13** [stinnux/kanboard-Timetrackingeditor#21]
Hello all,

I had the followin error:
Fatal error: Call to undefined method Kanboard\Plugin\Timetrackingeditor\Helper\SubtaskHelper::getTitle() in C:\idmHelper\PortableApps\usbwebserver8\root\kanboard\plugins\Timetrackingeditor\Helper\SubtaskHelper.php on line 38
in many different contexts. 
![image](https://user-images.githubusercontent.com/822698/33483427-1fc88976-d69e-11e7-915b-0cc6a807aeda.png)

Thanks in advance
Best regards
Tobias

**Comment by indrisepos** [comment]
Maybe replace the getTitle() to renderTitle() in plugins/Timetrackingeditor/Helper/SubtaskHelper.php

This line
`return $this->helper->url->link($this->renderTitle($subtask), 'SubtaskStatusController', 'change', $params, false, $class);`

Cange to:
`return $this->helper->url->link($this->getTitle($subtask), 'SubtaskStatusController', 'change', $params, false, $class);`

**Comment by stinnux** [comment]
Please try version 1.0.18
