### ISSUE TITLE
TimeTrackingEditor   no longer works with recent versions of kanboard

### ISSUE THREAD

**Issue by neiaberau** [stinnux/kanboard-Timetrackingeditor#22]
TimeTrackingEditor   no longer work, it produces the error: Internal Error: Identifier "sessionStorage" is not defined. this is probaly due session handling changes in kanboard in december 2017

**Comment by stinnux** [comment]
Please try Version 1.0.18

**Comment by neiaberau** [comment]
yes it does work with this version, thank you

and now I can test this, in my tests it seems to solve other issues as well
  - most inconsistencies in the kanboard "base time tracking" are solved as well when using this version, as it looks as it does and actual recalulation of the total time spent on each change 

- maybe the time edit on the task level should be disabled, as it gets ignored upon recalculation. I guess  as it does not do a time entry that can be summed. As I do not use this, not a big issue for me
