### ISSUE TITLE
Cannot edit entries

### ISSUE THREAD

**Issue by jmsalomr** [stinnux/kanboard-Timetrackingeditor#3]
When I try to edit an existing task, the dialog box form gets waiting indefinitely after submitting the Save button. I have to press cancel to come back and the time tracking entry remains unchanged.

Configuration:
Application version: 1.0.34
PHP version: 7.0.8-0ubuntu0.16.04.3
PHP SAPI: fpm-fcgi
OS version: Linux 4.4.0-45-generic
Database driver: mysql
Database version: 5.6.33-79.0-log
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36 OPR/41.0.2353.46

Tested with Opera and Chrome under Mac OS X 10.11.

**Comment by stinnux** [comment]
I think your version of kanboard may be incompatible with the plugin. 

Please try kanboard 1.0.38 with Timetrackingeditor 1.10
