### ISSUE TITLE
Timetrackingeditor incompatible with Kanboard 1.0.38

### ISSUE THREAD

**Issue by eparon** [stinnux/kanboard-Timetrackingeditor#4]
We used `Timetrackingeditor` in our installation of Kanboard (`v.1.0.36`).  
However, we recently updated Kanboard to their latest (as of now) version (`1.0.38`) and we're facing problems with this plugin. Specifically:
- When trying to add a new timetracking entry in a task, instead of getting a popup form, Kanboard opens a new tab with the link provided from the "Add new timetracking entry" button.
- When trying to click "Cancel", we get a `500 - Internal error`.

After some investigation on some other Kanboard links that have the same behavior (for instance, the "add internal link"), i observed the following:
- All the other links of such behavior, instead of the `class=popover` attribute, they have a `class=js-modal-medium`.
- The "Cancel" buttons of such links, instead of having the attribute `class=popover-close`, they just have an `<a href="#"/>` and nothing more.

If one plays with the "Inspect Element" option of modern web browsers and edits the html code according to my previous two remarks, then the behavior of Timetrackingeditor is correct again.

Probably we can change these things in the source code of the plugin as it is provided, but as we are not in favor of dirty hacks, is it possible to provide an official fix/update/new version of the plugin that fixes this issue?

**Comment by stinnux** [comment]
Nice to hear to you are working with the plugin. 

I am currently in the process of updating it, so that it will be compatible to the current version of kanboard. 

Thanks for all your analyzes, this will be of great help for me.

**Comment by eparon** [comment]
no problem! for anything more you might need from my side, feel free to ask!

**Comment by stinnux** [comment]
Please try the new Version 1.10, which is now compatible with Kanboard 1.0.38

**Comment by jmsalomr** [comment]
Hi,

It still fails when you push 'Start Timer'. It seems is the same issue.

Cloud you test it?

**Comment by eparon** [comment]
i can confirm now that the issue is resolved! thanks a lot @stinnux and keep creating awesome things 👍

**Comment by Colin-TUE** [comment]
For me When I press start time, it works. Only the cancel gives controller not found error. No big deal though.
