### ISSUE TITLE
Timetrackingeditor incompatible with Kanboard 1.0.38

### ISSUE THREAD

**Issue by jmsalomr** [stinnux/kanboard-Timetrackingeditor#7]
Hi,

It seems still fails when you push 'Start timer'. Could you test it?

Best regards.

**Comment by jmsalomr** [comment]
Hi,

I'm still checking. It also fails when you Cancel the dialog box in the Time tracking view.

**Comment by jmsalomr** [comment]
-

**Comment by stinnux** [comment]
Please Try 1.12

**Comment by jmsalomr** [comment]
Thanks !
